const cities = [
  {
    name: "Manali",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23",
    description: "Hill station popular for snow views, cafes, and adventure sports.",
    costPerDay: 2500,
    region: "North India",
  },
  {
    name: "Kasol",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1593181629936-11c609b8db9b",
    description: "Backpacker-friendly riverside village and trekking base.",
    costPerDay: 1800,
    region: "North India",
  },
  {
    name: "Shimla",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1622308644420-b20142dc993c",
    description: "Colonial-era hill town with scenic mountain walks.",
    costPerDay: 2200,
    region: "North India",
  },
  {
    name: "Leh",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1587474260584-136574528ed5",
    description: "High-altitude desert destination known for monasteries and road trips.",
    costPerDay: 3200,
    region: "North India",
  },
  {
    name: "Jaipur",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1477587458883-47145ed94245",
    description: "Historic forts, palaces, and vibrant local bazaars.",
    costPerDay: 2300,
    region: "West India",
  },
  {
    name: "Udaipur",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1599661046827-dacde6976542",
    description: "Romantic lake city with heritage architecture.",
    costPerDay: 2400,
    region: "West India",
  },
  {
    name: "Jaisalmer",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1599661046289-e31897846e41",
    description: "Golden desert city famous for forts and camel safaris.",
    costPerDay: 2600,
    region: "West India",
  },
  {
    name: "Goa",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2",
    description: "Beaches, nightlife, seafood, and Portuguese heritage.",
    costPerDay: 3000,
    region: "West India",
  },
  {
    name: "Mumbai",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1562979314-bee7453e911c",
    description: "Fast-paced city with food, culture, and coastal landmarks.",
    costPerDay: 3500,
    region: "West India",
  },
  {
    name: "Delhi",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1587474260584-136574528ed5",
    description: "Capital city blending history, street food, and modern neighborhoods.",
    costPerDay: 2800,
    region: "North India",
  },
  {
    name: "Varanasi",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc",
    description: "Ancient spiritual city known for ghats and Ganga aarti.",
    costPerDay: 1700,
    region: "North India",
  },
  {
    name: "Rishikesh",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1627894483216-2138af692e32",
    description: "Yoga capital with river rafting and mountain scenery.",
    costPerDay: 1900,
    region: "North India",
  },
  {
    name: "Darjeeling",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1622308644420-b20142dc993c",
    description: "Tea gardens, toy train, and Himalayan views.",
    costPerDay: 2100,
    region: "East India",
  },
  {
    name: "Kolkata",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1558431382-27e303142255",
    description: "Cultural capital known for heritage, food, and literature.",
    costPerDay: 2200,
    region: "East India",
  },
  {
    name: "Bengaluru",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2",
    description: "Garden city with cafes, startups, and pleasant weather.",
    costPerDay: 2600,
    region: "South India",
  },
  {
    name: "Mysuru",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1583417319070-4a69db38a482",
    description: "Palaces, markets, and traditional South Indian culture.",
    costPerDay: 1900,
    region: "South India",
  },
  {
    name: "Kochi",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1593693411515-c20261bcad6e",
    description: "Coastal city with backwaters, seafood, and colonial history.",
    costPerDay: 2200,
    region: "South India",
  },
  {
    name: "Pondicherry",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bada",
    description: "French-inspired coastal town with cafes and beaches.",
    costPerDay: 2300,
    region: "South India",
  },
  {
    name: "Bangkok",
    country: "Thailand",
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365",
    description: "Street food, temples, shopping, and vibrant nightlife.",
    costPerDay: 3500,
    region: "Southeast Asia",
  },
  {
    name: "Bali",
    country: "Indonesia",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4",
    description: "Beaches, temples, rice terraces, and surfing.",
    costPerDay: 4000,
    region: "Southeast Asia",
  },
  {
    name: "Dubai",
    country: "United Arab Emirates",
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c",
    description: "Luxury shopping, desert safaris, and modern architecture.",
    costPerDay: 7000,
    region: "Middle East",
  },
  {
    name: "Paris",
    country: "France",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    description: "Iconic landmarks, art museums, and cafes.",
    costPerDay: 8500,
    region: "Europe",
  }
];